name: CI main push
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install yarn
        run: npm install --global yarn

      - name: Set yarn version v4.x
        run: yarn set version berry

      - name: Check yarn version
        run: yarn --version

      - name: Set nodeLinker node-modules
        run: yarn config set nodeLinker node-modules

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
